// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are not used by any `pub` functions: `EventDetails`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginCallback>>
abstract class PluginCallback implements RustOpaqueInterface {
  Future<void> changeOnPrint(
      {required FutureOr<void> Function(String) onPrint});

  static Future<PluginCallback> default_() =>
      RustLib.instance.api.crateApiPluginPluginCallbackDefault();
}

abstract class SetonixPlugin {
  Future<EventResult> runEvent(
      {required String eventType,
      required String event,
      required String serverEvent,
      required int target});
}

class EventResult {
  final int target;
  final String? serverEvent;
  final Set<int>? needsUpdate;

  const EventResult({
    required this.target,
    this.serverEvent,
    this.needsUpdate,
  });

  @override
  int get hashCode =>
      target.hashCode ^ serverEvent.hashCode ^ needsUpdate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventResult &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          serverEvent == other.serverEvent &&
          needsUpdate == other.needsUpdate;
}
